### ISSUE TITLE
Tests fail with Cpanel::JSON::XS 3.0206

### ISSUE THREAD

**Issue by eserte** [Grinnz/Mojo-JSON-MaybeXS#1]
While it seems that the test suite works with Cpanel::JSON::XS 3.0207, it fails if an older version is installed:
```
, or ] expected while parsing array, at character offset 16387 (before "aaaaaaaaaaaaaaaaaaaa...") at /tmpfs/.cpan-build/2015120221/Mojo-JSON-MaybeXS-0.010-JhvSW_/blib/lib/Mojo/JSON/MaybeXS.pm line 28, <DATA> line 2125.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 90.
t/json.t ............... 
Dubious, test returned 255 (wstat 65280, 0xff00)
All 90 subtests passed 
```

**Comment by Grinnz** [comment]
Yes, because those versions are broken. The test suite is doing its job.

**Comment by eserte** [comment]
But it has the effect that the CPAN Testers Matrix for your module looks quite red now: http://fast-matrix.cpantesters.org/?dist=Mojo-JSON-MaybeXS%200.010

What about trying to repair the situation in Build.PL/Makefile.PL? You can easily do something like
```
    if (eval { require Cpanel::JSON::XS; $Cpanel::JSON::XS == 3.0206 }) {
       $min_cpanel_json_xs_version = '3.0207';
    }
    ...
    PREREQ_PM => {
        ($min_cpanel_json_xs_version ? ('Cpanel::JSON::XS' => $min_cpanel_json_xs_version) : ()),
    },
```
(or the equivalent for Build.PL) (untested)

At least it would be good to print some diagnostics in this test, and point the user into a Cpanel::JSON::XS upgrade.

**Comment by Grinnz** [comment]
I would be more inclined to add a conflicts entry, but I really don't feel it's that important; these versions have only been out for a few days, the smokers just happen to have them installed because 3.0207 just came out.
