### ISSUE TITLE
\!!0 encodes to null, not false

### ISSUE THREAD

**Issue by akarelas** [Grinnz/Mojo-JSON-MaybeXS#2]
This is quite different from Mojo::JSON, where we type \!!$var to get either true or false.

I use Cpanel::JSON::XS version 3.0213
I use Mojo::JSON::MaybeXS version 0.010

See here for my test code: http://paste.scsys.co.uk/508110?ln=on&hl=on&submit=Format+it!

**Comment by Grinnz** [comment]
!!0 results in the Perl "false" value, and a scalar ref to that is not the same as a scalar ref to 0 (which is the only thing JSON::PP/JSON::XS/Cpanel::JSON::XS supports as a scalar ref for encoding to `false`). So it gets encoded to null as per https://metacpan.org/pod/Mojo::JSON::MaybeXS#Unblessed-References.

**Comment by akarelas** [comment]
Then this module isn't very compatible with Mojo::JSON.

**Comment by Grinnz** [comment]
The known incompatibilities are plainly listed in the documentation. There is not much that can be done except attempt to convince the underlying modules to change their longstanding behavior.

**Comment by akarelas** [comment]
Let's all ask them (politely) to change their longstanding behaviour.
