### ISSUE TITLE
update docs with new reality vs. Mojo::JSON

### ISSUE THREAD

**Issue by karenetheridge** [Grinnz/Mojo-JSON-MaybeXS#4]
Mojolicious 7.87's Mojo::JSON now automatically binds to Cpanel::JSON::XS's interfaces when it is installed - so something should be updated in the docs to reflect this.  (e.g. Is Mojo::JSON::MaybeXS now redudant with the latest Mojolicious? Are there other edge cases to consider?)

**Comment by karenetheridge** [comment]
*gentle nudge*

**Comment by Grinnz** [comment]
Docs have been updated in 1.002.
